### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by edamron** [JeffreyGarrett/kudosSlackApp#1]
Any chance of getting a very basic set of install instructions??

Thanks!

**Comment by JeffreyGarrett** [comment]
Ya, I'll be working on some updates this weekend as updates to slack have broken the app.  When I do so I'll add easy installation instructions.

**Comment by JeffreyGarrett** [comment]
The instructions have been updated.  Please let me know if something isn't working as documented or submit a pull request with the updates.  

Thanks!

**Comment by JeffreyGarrett** [comment]
closing issue for now
